---
language: python
services: redis-server
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
install:
 - pip install tox~=2.3.2 tox-travis~=0.6.0
script: tox
after_success: bash <(curl -s https://codecov.io/bash)
